# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d088ee59baac3178c26448b541cbd2e55ad8e69d5e14b3925e3e4ee5a5745ea65ccf9d5770064055c23465ab44b8c8bdedfb9cbacc71feac81d1bb3fa6e3d92

test:
  secret_key_base: d752cc9276e142efe9c1dc20f7cc44a23f0cc647c1783693c089972af7452a192668f0ba46873e7357846453ff40e5e2b3ac6de520a539de75f1f4f9a7181834

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
